### PR TITLE
Fix some URLs for attributes and commands

### PR DESCRIPTION
**Pull request by bourtemb**
Fix URL for attributes values, info, properties, history and command history.
Attribute name and command name were missing.

### CODE REVIEW

**Comment by Ingvord** [comment]
Will be released shortly in 1.15

**Comment by Ingvord** [comment]
@bourtemb , thanks for the contribution!!!

**Comment by bourtemb** [comment]
Ooops, it seems this was fixing the URLs when http://.../tango/rest/rc4/hosts/my_tango_host/10000/devices/sys/tg_test/1/attributes is requested but then the URL are wrong when http://.../tango/rest/rc4/hosts/acudebian7/10000/devices/test/universal/1/attributes/ampli is requested.

So my proposed fixed is also causing some issues in some cases it seems... Sorry about that...

**Comment by Ingvord** [comment]
No worries. This is not critical.

As an exercise you can write a test that enforces correct behavior [here](https://github.com/tango-controls/rest-test-suite)  :)

**Comment by bourtemb** [comment]
Another possible fix might be to revert my PR and to apply the following patch:
```
diff --git a/src/main/java/org/tango/rest/rc4/JaxRsDevice.java b/src/main/java/org/tango/rest/rc4/JaxRsDevice.java
index 9347ea9..b9cd43d 100644
--- a/src/main/java/org/tango/rest/rc4/JaxRsDevice.java
+++ b/src/main/java/org/tango/rest/rc4/JaxRsDevice.java
@@ -68,7 +68,7 @@ public class JaxRsDevice {
                 Arrays.asList(deviceProxy.getProxy().toDeviceProxy().get_attribute_info_ex()), new Function<AttributeInfoEx, Object>() {
                     @Override
                     public Object apply(final AttributeInfoEx input) {
-                        return DeviceHelper.attributeInfoExToResponse(input.name, href);
+                        return DeviceHelper.attributeInfoExToResponse(input.name, href + "/" + input.name);
                     }
                 });
     }
@@ -134,7 +134,7 @@ public class JaxRsDevice {
         return Lists.transform(Arrays.asList(deviceProxy.getProxy().toDeviceProxy().command_list_query()), new Function<CommandInfo, Object>() {
             @Override
             public Object apply(final CommandInfo input) {
-                return DeviceHelper.commandInfoToResponse(input, href);
+                return DeviceHelper.commandInfoToResponse(input, href + "/" + input.cmd_name);
             }
         });
     }
```

> As an exercise you can write a test that enforces correct behavior [here](https://github.com/tango-controls/rest-test-suite) :)

Good exercise indeed...

**Comment by Ingvord** [comment]
I have reverted this PR in #186 

Could you please apply your changes/patch there? Thanks!

**Comment by bourtemb** [comment]
> I have reverted this PR in #186
> 
> Could you please apply your changes/patch there? Thanks!

Done!

**Pull request merged**
